export const products = [
  {
    id: "1",
    title: "Валенсия Beige",
    category: "Стулья",
    img: "card-01",
    qty: 1,
    price: 3750,
    oldprice: 5000,
    sum: 0,
    oldsum: 0,
    discount: true,
    discountAmount: "-25%",
    colour: "Бежевый",
    colourClass: "_beige",
    size: {
      width: "218",
      height: "90",
      depth: "70",
    },
  },
  {
    id: "2",
    title: "Толикс-2 White Gloss",
    category: "Стулья",
    img: "card-02",
    price: 4000,
    oldprice: 6000,
    sum: 0,
    oldsum: 0,
    discount: false,
    discountAmount: "-25%",
    colour: "Белый",
    colourClass: "_white",
    qty: 1,
    size: {
      width: "118",
      height: "50",
      depth: "50",
    },
  },
  {
    id: "3",
    title: "Динс Velvet Yellow Динс Velvet Yellow Динс Velvet Yellow Динс Velvet Yellow",
    category: "Диваны",
    img: "card-03",
    price: 7500,
    oldprice: 10000,
    sum: 0,
    oldsum: 0,
    discount: true,
    discountAmount: "-25%",
    colour: "Жёлтый",
    colourClass: "_yellow",
    qty: 1,
    size: {
      width: "318",
      height: "330",
      depth: "90",
    },
  },
  {
    id: "4",
    title: "Шерона Barhat Grey",
    category: "Двуспальные кровати",
    img: "card-05",
    price: 10000,
    oldprice: 15000,
    sum: 0,
    oldsum: 0,
    discount: false,
    discountAmount: "-25%",
    colour: "Тёмно-серый",
    colourClass: "_dark-grey",
    qty: 1,
    size: {
      width: "118",
      height: "40",
      depth: "20",
    },
  },
  {
    id: "5",
    title: "Бенфлит Grey",
    category: "Журнальные столы",
    img: "card-09",
    price: 2000,
    oldprice: 3000,
    sum: 0,
    oldsum: 0,
    discount: false,
    discountAmount: "-25%",
    colour: "Серый",
    colourClass: "_grey",
    qty: 1,
    size: {
      width: "118",
      height: "40",
      depth: "20",
    },
  },
  {
    id: "6",
    title: "Вилли Pink",
    category: "Детский диван",
    img: "card-13",
    price: 3500,
    oldprice: 4375,
    sum: 0,
    oldsum: 0,
    discount: true,
    discountAmount: "-25%",
    colour: "Розовый",
    colourClass: "_pink",
    qty: 1,
    size: {
      width: "118",
      height: "40",
      depth: "20",
    },
  },
  {
    id: "7",
    title: "Сан-Паулу Velvet Brown",
    category: "Диваны",
    img: "card-14",
    price: 6500,
    oldprice: 10000,
    sum: 0,
    oldsum: 0,
    discount: false,
    discountAmount: "-25%",
    colour: "Бархатно-коричневый",
    colourClass: "_velvet-brown",
    qty: 1,
    size: {
      width: "118",
      height: "40",
      depth: "20",
    },
  },
  {
    id: "8",
    title: "Стелла Дуб Сонома",
    category: "Комоды",
    img: "card-08",
    price: 1500,
    oldprice: 3000,
    sum: 0,
    oldsum: 0,
    discount: true,
    discountAmount: "-50%",
    colour: "Белый",
    colourClass: "_white",
    qty: 1,
    size: {
      width: "118",
      height: "40",
      depth: "20",
    },
  },
];
